#!/bin/sh

export cwd="$(pwd)"
export __dirname="$(dirname "$(realpath "$0")")"

export os="linux"
export arch="arm64"

export name="$(jq -r '.name' package.json)"
export version="$(jq -r '.version' package.json)"
export description="$(jq -r '.description' package.json)"
export maintainer="$(jq -r '.author' package.json)"

export host="releases.hashicorp.com"
export keyuid="HashiCorp Security <security@hashicorp.com>"
#export keyprint="91A6 E7F8 5D05 C656 30BE  F189 5185 2D87 348F FC4C"
#export keyprint="E8A0 32E0 94D8 EB4E A189 D270 DA41 8C88 A321 9F7B"
export keyprint="C874 011F 0AB4 0511 0D02 1055 3436 5D94 72D7 468F"
export bin='/usr/bin'
export sha='256'

export base="${name}_${version}"
export zipfile="${base}_${os}_${arch}.zip"
export sumfile="${base}_SHA${sha}SUMS"
export sigfile="${base}_SHA${sha}SUMS.sig"

export builds="${cwd}/.builds"
export downloads="${cwd}/.downloads"
export packages="${cwd}/.packages"

if ! hash curl dpkg jq 2>/dev/null ; then
  echo "Enter your password to install dependencies"
  sudo -v
  if [ `uname` == 'Darwin' ]; then
    brew install curl dpkg jq
  elif [ `uname` == 'Linux' ]; then
    sudo apt-get curl install dpkg jq
  else
    fail "dpkg and jq is required"
  fi
fi
